version: "3"

services:
  quad_front:
    build:
      context: ./front
      args:
        API_URL: ${API_URL}
    container_name: quad_front
    command: serve -s build -l 3003
    restart: unless-stopped
    ports:
      - "3003:3003"
    logging:
      options:
        max-size: 10m
    # before run cmd:  docker network create dock-vv-network
    networks:
      - v1-network

  quad_api:
    build: ./back
    container_name: quad_api
    command: npm run start
    restart: unless-stopped
    environment:
      - API_PORT=${API_PORT}
    volumes:
      - ./logs:/usr/src/app/logs
    ports:
      - "${API_PORT}:${API_PORT}"
    logging:
      options:
        max-size: 10m
    networks:
      - v1-network

networks:
  v1-network:
    external: true
